# Généré par PNCconf le Sun Apr  5 19:47:42 2026
# Utilise la version LinuxCNC :  Master (2.9)
# Si vous modifiez ce fichier, il sera
# écrasé quand vous relancerez PNCconf

[EMC]
MACHINE = ProducMillCV30
DEBUG = 0
VERSION = 1.1

[DISPLAY]
DISPLAY = axis
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_FEED_OVERRIDE = 2.000000
MAX_SPINDLE_OVERRIDE = 1.000000
MIN_SPINDLE_OVERRIDE = 0.500000
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
PROGRAM_PREFIX = /home/cnc/linuxcnc/nc_files
INCREMENTS = 5mm 1mm .5mm .1mm .05mm .01mm .005mm
POSITION_FEEDBACK = ACTUAL
DEFAULT_LINEAR_VELOCITY = 6.000000
MAX_LINEAR_VELOCITY = 100.000000
MIN_LINEAR_VELOCITY = 0.500000
DEFAULT_ANGULAR_VELOCITY = 12.000000
MAX_ANGULAR_VELOCITY = 180.000000
MIN_ANGULAR_VELOCITY = 1.666667
EDITOR = gedit
GEOMETRY = xyz
CYCLE_TIME = 100

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[RS274NGC]
PARAMETER_FILE = linuxcnc.var
RS274NGC_STARTUP_CODE = G21 G40 G90 G94 G97 G64 P0.025

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 1000000

[HMOT]
# **** This is for info only ****
CARD0=hm2_7i96s.0

[HAL]
HALUI = halui
HALFILE = ProducMillCV30.hal
HALFILE = custom.hal
POSTGUI_HALFILE = custom_postgui.hal
SHUTDOWN = shutdown.hal

[HALUI]

[KINS]
JOINTS = 3
KINEMATICS = trivkins coordinates=XYZ

[TRAJ]
COORDINATES =  XYZ
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
DEFAULT_LINEAR_VELOCITY = 20.00
MAX_LINEAR_VELOCITY = 100.00

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl
TOOL_CHANGE_QUILL_UP = 1

#******************************************
[AXIS_X]
MAX_VELOCITY = 500.0
MAX_ACCELERATION = 900.0
MIN_LIMIT = -0.01
MAX_LIMIT = 200.0

[JOINT_0]
TYPE = LINEAR
HOME = 0.0

# Limites de l'axe
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 250.0

# Vitesse et accélération du générateur (avec ratio 2.1)
STEPGEN_MAXVEL = 270
STEPGEN_MAXACCEL = 350

P = 25.0
I = 0.0
D = 3.5
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.002
FERROR = 1.0
MIN_FERROR = 0.2

MAX_OUTPUT = 0.0
# these are in nanoseconds
DIRSETUP   = 2000
DIRHOLD    = 2000
STEPLEN    = 2000
STEPSPACE  = 2000
#  10000 driver gear ratio / 5 (vis) * ratio 2.1 ( poulie ) 
STEP_SCALE = -4200.0

MIN_LIMIT = -0.01
MAX_LIMIT = 200.0
HOME_OFFSET = 0.000000
HOME_SEARCH_VEL = 10.000000
HOME_LATCH_VEL = 0.500000
HOME_FINAL_VEL = 0.000000
HOME_USE_INDEX = NO
HOME_SEQUENCE = 2
#******************************************

#******************************************
[AXIS_Y]
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 250.0
MIN_LIMIT = -0.01
MAX_LIMIT = 200.0

[JOINT_1]
TYPE = LINEAR
HOME = 0.0

# Limites de l'axe
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 250.0

# Vitesse et accélération du générateur (avec ratio 2.1)
STEPGEN_MAXVEL = 270
STEPGEN_MAXACCEL = 350

P = 25.0
I = 0.0
D = 3.5
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.002
FERROR = 1.0
MIN_FERROR = 0.2

MAX_OUTPUT = 0.0
# these are in nanoseconds
DIRSETUP   = 2000
DIRHOLD    = 2000
STEPLEN    = 2000
STEPSPACE  = 2000
STEP_SCALE = -4200.0

MIN_LIMIT = -0.01
MAX_LIMIT = 200.0
HOME_OFFSET = 0.000000
HOME_SEARCH_VEL = 10.000000
HOME_LATCH_VEL = 0.500000
HOME_FINAL_VEL = 0.000000
HOME_USE_INDEX = NO
HOME_SEQUENCE = 2
#******************************************

#******************************************
[AXIS_Z]
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 250.0
MIN_LIMIT = 0
MAX_LIMIT = 200

[JOINT_2]
TYPE = LINEAR
HOME = 0.0
# Limites de l'axe
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 250.0

# Vitesse et accélération du générateur (avec ratio 2.1)
STEPGEN_MAXVEL = 270
STEPGEN_MAXACCEL = 350

P = 25.0
I = 0.0
D = 3.5
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.002
FERROR = 1.0
MIN_FERROR = 0.2

MAX_OUTPUT = 0.0
# these are in nanoseconds
DIRSETUP   = 2000
DIRHOLD    = 2000
STEPLEN    = 2000
STEPSPACE  = 2000
STEP_SCALE = 4200.0

MIN_LIMIT = 0
MAX_LIMIT = 200
HOME_OFFSET = 200
HOME_SEARCH_VEL = -10.000000
HOME_LATCH_VEL = 0.50000
HOME_FINAL_VEL = 10
HOME_USE_INDEX = NO
HOME_SEQUENCE = 1
#******************************************

[SPINDLE_0]
P = 0.0
I = 0.0
D = 0.0
FF0 = 1.0
FF1 = 0.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 3000.0
ENCODER_SCALE = 4.0
OUTPUT_SCALE = 3000
OUTPUT_MIN_LIMIT = -3000
OUTPUT_MAX_LIMIT = 3000

